apiVersion: v1
name: kms-chart
description: A Helm chart for the ACK service controller for AWS Key Management Service (KMS)
version: v0.0.20
appVersion: v0.0.20
home: https://github.com/aws-controllers-k8s/kms-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/kms-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: KMS Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/kms-maintainer
keywords:
  - aws
  - kubernetes
  - kms
